name: Run UI-tests

on:
  workflow_dispatch:
    inputs:
      simulator:
        type: choice
        description: 'Select simulator'
        required: true
        default: '["iPhone 14"]'
        options:
        - '["iPhone 14"]'
        - '["iPhone 14 Pro"]'
      agent:
        type: choice
        description: 'Build agent'
        required: true
        default: macOS-latest
        options: 
        - macOS-latest
        - self_mac

env:
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"

jobs:
  all:
    runs-on: ${{ github.event.inputs.agent || 'macOS-latest' }}
    timeout-minutes: 60

    env:
      TEST_SIMULATOR: ${{ github.event.inputs.simulator  || '["iPhone 11"]' }}
      ALLURE_PROJECT_ID: $TESTOPS_PROJECT_ID
      ALLURE_ENDPOINT: ${{ secrets.TESTOPS_ENDPOINT_URL }}
      ALLURE_TOKEN: ${{ secrets.TESTOPS_TOKEN }}


    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Ruby 💎
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.5

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install brew dependencies
      run: brew bundle

    - name: Install rubygems
      run: bundle install

    - name: Print
      run: |
        env
        echo $TESTOPS_PROJECT_ID

    - name: Build app
      run: bundle exec fastlane ios build_test_app

    - name: Run tests
      run: bundle exec fastlane ios run_tests

    - name: Install xcresult 
      run: |
        wget https://github.com/eroshenkoam/xcresults/releases/latest/download/xcresults
        chmod +x ./xcresults

    - name: Convert xcresult to allure results
      run: xcresults export ./Report/SimpleCalculator.xcresult ./allure-results

    - name: Install allurectl 
      run: |
        wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_darwin_amd64 -O ./allurectl
        chmod +x ./allurectl

    # - name: Export test results to TestOPS
    #   run: pwd

    - name: Send slack message
      run: bundle exec fastlane ios slack_result slack_url:${{ secrets.SLACK_WEBHOOK_URL }}
