name: Run UI-tests

on:
  workflow_dispatch:
    inputs:
      simulator:
        type: choice
        description: 'Select simulator'
        required: true
        default: '["iPhone 11"]'
        options:
        - '["iPhone 11"]'
        - '["iPhone 14 Pro"]'
      agent:
        type: choice
        description: 'Build agent'
        required: true
        default: macOS-latest
        options: 
        - macOS-latest
        - self_mac

env:
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"



jobs:
  all:
    runs-on: ${{ github.event.inputs.agent || 'macOS-latest' }}
    timeout-minutes: 60

    env:
      TEST_SIMULATOR: ${{ github.event.inputs.simulator  || '["iPhone 11"]' }}
      ALLURE_PROJECT_ID: ${{ env.TESTOPS_PROJECT_ID }}
      ALLURE_ENDPOINT: ${{ secrets.TESTOPS_ENDPOINT_URL }}
      ALLURE_TOKEN: ${{ secrets.TESTOPS_TOKEN }}


    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Ruby 💎
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.5

    - name: Install brew dependencies
      run: pwd

    - name: Install rubygems
      run: pwd

    - name: Build app
      run: pwd

    - name: Run tests
      run: pwd

    - name: Export test results
      run: pwd

    - name: Send slack message 
      run: pwd
